[2025-01-08T13:45:38.751+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.preprocess_to_staging manual__2025-01-08T13:43:21.507471+00:00 [queued]>
[2025-01-08T13:45:38.790+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.preprocess_to_staging manual__2025-01-08T13:43:21.507471+00:00 [queued]>
[2025-01-08T13:45:38.791+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T13:45:38.818+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): preprocess_to_staging> on 2025-01-08 13:43:21.507471+00:00
[2025-01-08T13:45:38.833+0000] {standard_task_runner.py:57} INFO - Started process 799 to run task
[2025-01-08T13:45:38.841+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'preprocess_to_staging', 'manual__2025-01-08T13:43:21.507471+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp2mbl22sa']
[2025-01-08T13:45:38.846+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask preprocess_to_staging
[2025-01-08T13:45:38.874+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:45:38.942+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.preprocess_to_staging manual__2025-01-08T13:43:21.507471+00:00 [running]> on host f5be33ae8d70
[2025-01-08T13:45:39.114+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T13:43:21.507471+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-08T13:43:21.507471+00:00'
[2025-01-08T13:45:39.116+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:45:39.117+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/scripts/preprocess_to_staging.py --bucket_raw raw --db_host mysql --db_user root --db_password root --endpoint-url http://localstack:4566']
[2025-01-08T13:45:39.134+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:45:44.380+0000] {subprocess.py:93} INFO - Récupération des données depuis le bucket raw...
[2025-01-08T13:45:44.433+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données depuis S3: Unable to locate credentials
[2025-01-08T13:45:45.527+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-08T13:45:45.610+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=preprocess_to_staging, execution_date=20250108T134321, start_date=20250108T134538, end_date=20250108T134545
[2025-01-08T13:45:45.728+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-08T13:45:45.802+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
