[2025-01-08T13:45:48.796+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_curated manual__2025-01-08T13:43:21.507471+00:00 [queued]>
[2025-01-08T13:45:48.835+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_curated manual__2025-01-08T13:43:21.507471+00:00 [queued]>
[2025-01-08T13:45:48.837+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T13:45:48.884+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_to_curated> on 2025-01-08 13:43:21.507471+00:00
[2025-01-08T13:45:48.913+0000] {standard_task_runner.py:57} INFO - Started process 823 to run task
[2025-01-08T13:45:48.930+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'process_to_curated', 'manual__2025-01-08T13:43:21.507471+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpltyl0xrr']
[2025-01-08T13:45:48.955+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask process_to_curated
[2025-01-08T13:45:49.030+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:45:49.155+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.process_to_curated manual__2025-01-08T13:43:21.507471+00:00 [running]> on host f5be33ae8d70
[2025-01-08T13:45:49.393+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='process_to_curated' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T13:43:21.507471+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-08T13:43:21.507471+00:00'
[2025-01-08T13:45:49.397+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:45:49.400+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/scripts/process_to_curated.py --mysql_host mysql --mysql_user root --mysql_password root --mongo_uri mongodb://mongodb:27017/']
[2025-01-08T13:45:49.425+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:45:51.929+0000] {subprocess.py:93} INFO - None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[2025-01-08T13:45:52.975+0000] {subprocess.py:93} INFO - /opt/***/scripts/process_to_curated.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-01-08T13:45:52.977+0000] {subprocess.py:93} INFO -   df = pd.read_sql(query, connection)
[2025-01-08T13:45:52.978+0000] {subprocess.py:93} INFO - Récupération des données depuis MySQL...
[2025-01-08T13:45:52.979+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données MySQL: Execution failed on sql 'SELECT id, text FROM texts': 1146 (42S02): Table 'staging.texts' doesn't exist
[2025-01-08T13:45:52.979+0000] {subprocess.py:93} INFO - Aucune donnée récupérée depuis MySQL
[2025-01-08T13:45:53.196+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-08T13:45:53.238+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=process_to_curated, execution_date=20250108T134321, start_date=20250108T134548, end_date=20250108T134553
[2025-01-08T13:45:53.263+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-08T13:45:53.287+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
