[2025-01-08T13:43:53.284+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_curated scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:43:53.314+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_curated scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-01-08T13:43:53.316+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T13:43:53.373+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_to_curated> on 2025-01-01 00:00:00+00:00
[2025-01-08T13:43:53.392+0000] {standard_task_runner.py:57} INFO - Started process 271 to run task
[2025-01-08T13:43:53.406+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'process_to_curated', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpxlm_k793']
[2025-01-08T13:43:53.423+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask process_to_curated
[2025-01-08T13:43:53.491+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:43:53.648+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.process_to_curated scheduled__2025-01-01T00:00:00+00:00 [running]> on host f5be33ae8d70
[2025-01-08T13:43:53.986+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='process_to_curated' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-01-08T13:43:53.995+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:43:53.996+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/scripts/process_to_curated.py --mysql_host mysql --mysql_user root --mysql_password root --mongo_uri mongodb://mongodb:27017/']
[2025-01-08T13:43:54.017+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:43:56.244+0000] {subprocess.py:93} INFO - The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
[2025-01-08T13:43:56.321+0000] {subprocess.py:93} INFO - 0it [00:00, ?it/s]0it [00:00, ?it/s]
[2025-01-08T13:43:56.321+0000] {subprocess.py:93} INFO - None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[2025-01-08T13:43:57.548+0000] {subprocess.py:93} INFO - /opt/***/scripts/process_to_curated.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-01-08T13:43:57.551+0000] {subprocess.py:93} INFO -   df = pd.read_sql(query, connection)
[2025-01-08T13:43:57.551+0000] {subprocess.py:93} INFO - Récupération des données depuis MySQL...
[2025-01-08T13:43:57.552+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données MySQL: Execution failed on sql 'SELECT id, text FROM texts': 1146 (42S02): Table 'staging.texts' doesn't exist
[2025-01-08T13:43:57.553+0000] {subprocess.py:93} INFO - Aucune donnée récupérée depuis MySQL
[2025-01-08T13:43:57.724+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-08T13:43:57.758+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=process_to_curated, execution_date=20250101T000000, start_date=20250108T134353, end_date=20250108T134357
[2025-01-08T13:43:57.801+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-08T13:43:57.826+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
