[2025-01-08T13:44:05.075+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_curated scheduled__2025-01-02T00:00:00+00:00 [queued]>
[2025-01-08T13:44:05.093+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_lake_pipeline.process_to_curated scheduled__2025-01-02T00:00:00+00:00 [queued]>
[2025-01-08T13:44:05.095+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-01-08T13:44:05.119+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_to_curated> on 2025-01-02 00:00:00+00:00
[2025-01-08T13:44:05.126+0000] {standard_task_runner.py:57} INFO - Started process 351 to run task
[2025-01-08T13:44:05.132+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_lake_pipeline', 'process_to_curated', 'scheduled__2025-01-02T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpr6dlvd6y']
[2025-01-08T13:44:05.140+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask process_to_curated
[2025-01-08T13:44:05.169+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-08T13:44:05.222+0000] {task_command.py:415} INFO - Running <TaskInstance: data_lake_pipeline.process_to_curated scheduled__2025-01-02T00:00:00+00:00 [running]> on host f5be33ae8d70
[2025-01-08T13:44:05.351+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_lake_pipeline' AIRFLOW_CTX_TASK_ID='process_to_curated' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-02T00:00:00+00:00'
[2025-01-08T13:44:05.356+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-08T13:44:05.358+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/scripts/process_to_curated.py --mysql_host mysql --mysql_user root --mysql_password root --mongo_uri mongodb://mongodb:27017/']
[2025-01-08T13:44:05.374+0000] {subprocess.py:86} INFO - Output:
[2025-01-08T13:44:07.246+0000] {subprocess.py:93} INFO - None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[2025-01-08T13:44:08.047+0000] {subprocess.py:93} INFO - /opt/***/scripts/process_to_curated.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-01-08T13:44:08.049+0000] {subprocess.py:93} INFO -   df = pd.read_sql(query, connection)
[2025-01-08T13:44:08.049+0000] {subprocess.py:93} INFO - Récupération des données depuis MySQL...
[2025-01-08T13:44:08.050+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données MySQL: Execution failed on sql 'SELECT id, text FROM texts': 1146 (42S02): Table 'staging.texts' doesn't exist
[2025-01-08T13:44:08.051+0000] {subprocess.py:93} INFO - Aucune donnée récupérée depuis MySQL
[2025-01-08T13:44:08.235+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-08T13:44:08.274+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=data_lake_pipeline, task_id=process_to_curated, execution_date=20250102T000000, start_date=20250108T134405, end_date=20250108T134408
[2025-01-08T13:44:08.302+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-08T13:44:08.330+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
